server:
  port: 8287
spring:
  application:
    name: reggie-jpa
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://52.199.163.241:5432/reggie
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
# 自定義傳入文件根目錄路徑
reggie:
  path: classpath:/images/reggie-foods