server:
  port: 8287
spring:
  application:
    name: reggie-new-deal
  datasource:
    driver-class-name: oracle.driver.OracleDriver
    url: jdbc:oracle:thin://127.0.0.1:1521/XEPDB1
    username: ORACLECT
    password: ORACLECT
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: ORACLE
    show-sql: true
    open-in-view: false
# 自定義傳入文件根目錄路徑
reggie:
  path: D:\VSCode\JavaKaiHatsu\ReggieFoods\